# Generated by Django 6.0.5 on 2026-05-06 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locataire', '0001_initial'),
        ('Proprietaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=12, unique=True)),
                ('cin', models.CharField(max_length=10, unique=True)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Baux',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_debut', models.DateField()),
                ('date_sortie', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Agents.agents')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Locataire.locataire')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Proprietaire.proprietaire')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Proprietaire.propriete')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('prix_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_contrat', models.DateField()),
                ('date_finContrat', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Agents.agents')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Proprietaire.propriete')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date_offre', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='Agents.agents')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='Proprietaire.propriete')),
            ],
        ),
    ]
