# Generated by Django 6.0.4 on 2026-04-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locataire', '0001_initial'),
        ('Proprietaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('matricule', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('CIN', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_debut', models.DateField()),
                ('date_sortie', models.DateField()),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Locataire.locataire')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Proprietaire.proprietaire')),
            ],
        ),
    ]
