# Generated by Django 6.0.4 on 2026-04-27 20:40

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baux',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_debut', models.DateField()),
                ('date_sortie', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('prix_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_contrat', models.DateField()),
                ('date_finContrat', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricule', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('CIN', models.CharField(max_length=10, unique=True)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='agents_groups', related_query_name='agent', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='agents_permissions', related_query_name='agent', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
