# Generated by Django 6.0.4 on 2026-05-01 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agents', '0001_initial'),
        ('Locataire', '0001_initial'),
        ('Proprietaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baux',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Locataire.locataire'),
        ),
        migrations.AddField(
            model_name='baux',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Proprietaire.proprietaire'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Agents.agents'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Proprietaire.propriete'),
        ),
    ]
