# Generated by Django 6.0.4 on 2026-04-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0001_initial'),
        ('Proprietaire', '0002_propriete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('prix_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_contrat', models.DateField()),
                ('date_finContrat', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Agents.agents')),
                ('proriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Proprietaire.propriete')),
            ],
        ),
    ]
