# Generated by Django 4.2.30 on 2026-04-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proprietaire', '0001_initial'),
        ('Agents', '0001_initial'),
        ('Locataire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Proprietaire.propriete'),
        ),
        migrations.AddField(
            model_name='baux',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Locataire.locataire'),
        ),
        migrations.AddField(
            model_name='baux',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Proprietaire.proprietaire'),
        ),
    ]
