# Generated by Django 6.0.4 on 2026-04-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0002_contrat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='proriete',
            new_name='propriete',
        ),
        migrations.AlterField(
            model_name='baux',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
