# Generated by Django 6.0.5 on 2026-05-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baux',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
