# Generated by Django 6.0.4 on 2026-04-27 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agents', '0002_initial'),
        ('Proprietaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baux',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baux', to='Proprietaire.proprietaire'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Agents.agents'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Proprietaire.propriete'),
        ),
    ]
