# Generated by Django 6.0.5 on 2026-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0003_alter_baux_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
