# Generated by Django 6.0.5 on 2026-05-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0005_alter_contrat_id_alter_offre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_finContrat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
