# Generated by Django 6.0.5 on 2026-05-06 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proprietaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=10, unique=True)),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locataire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
            },
        ),
        migrations.CreateModel(
            name='demandeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('date_entre', models.DateField()),
                ('date_sortie', models.DateField()),
                ('dateDemande', models.DateField()),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeLocation', to='Proprietaire.propriete')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locataire.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locataire.locataire')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Maintenance', to='Proprietaire.propriete')),
            ],
        ),
    ]
