# Generated by Django 6.0.5 on 2026-05-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locataire', '0001_initial'),
        ('Proprietaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandelocation',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeLocation', to='Proprietaire.propriete'),
        ),
    ]
