# Generated by Django 6.0.5 on 2026-05-05 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locataire', '0002_initial'),
        ('Proprietaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locataire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandelocation',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locataire.locataire'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locataire.locataire'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Maintenance', to='Proprietaire.propriete'),
        ),
    ]
