# Generated by Django 6.0.5 on 2026-05-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locataire', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='cin',
            field=models.CharField(max_length=10),
        ),
    ]
