# Generated by Django 6.0.5 on 2026-05-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locataire', '0004_alter_locataire_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
