# Generated by Django 4.2.30 on 2026-04-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Propriétaire',
                'verbose_name_plural': 'Propriétaires',
            },
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=250, unique=True)),
                ('etat', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Proprietaire/')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to='Proprietaire.proprietaire')),
            ],
        ),
    ]
