# Generated by Django 6.0.4 on 2026-04-29 12:25

import Proprietaire.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('Cin', models.CharField(max_length=10, unique=True)),
                ('Telephone', models.CharField(max_length=10, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to .', related_name='proprietaire_groups', related_query_name='proprietauire', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='soecufu permissions for this user.', related_name='proprietaire_permissions', related_query_name='proprietaire', to='auth.permission', verbose_name='proprietaire permssion')),
            ],
            options={
                'verbose_name': 'Proprietaire',
                'verbose_name_plural': 'Proprietaire',
            },
            managers=[
                ('objects', Proprietaire.models.ProprietaireManager()),
            ],
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ville', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=250, unique=True)),
                ('etat', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='Proprietaire/')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
