# Generated by Django 6.0.5 on 2026-05-05 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proprietaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to='Proprietaire.proprietaire'),
        ),
    ]
