# Generated by Django 6.0.4 on 2026-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proprietaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
