# Generated by Django 6.0.4 on 2026-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proprietaire', '0002_alter_proprietaire_email_alter_propriete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='Cin',
            field=models.CharField(max_length=10),
        ),
    ]
