# Generated by Django 6.0.4 on 2026-04-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proprietaire', '0003_alter_proprietaire_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='Telephone',
            field=models.CharField(max_length=10),
        ),
    ]
