# Generated by Django 4.2.30 on 2026-05-05 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administrateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
